# Generated by Django 3.2.16 on 2024-09-23 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_follow_follow_unq'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='follow_unq',
        ),
    ]
